In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("Matplotlib:", plt.matplotlib.__version__)
print("Seaborn:", sns.__version__)


NumPy: 1.24.3
Pandas: 2.0.3
Matplotlib: 3.7.2
Seaborn: 0.12.2


In [3]:
import pandas as pd

df = pd.read_csv("/Users/zeynepeski/Downloads/car_fuel_efficiency.csv")
df.head(10)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   
5                  190            3.0         NaN     2484.883986   
6                  240            7.0       127.0     3006.542287   
7                  150            4.0       239.0     3638.657780   
8                  250            1.0       174.0     2714.219310   
9                  150            4.0       123.0     3509.036569   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
5          14.7        2008  Europe  Gasoline    All-wheel drive       -1.0   
6          22.2        2012     USA  Gasoline  Front-wheel drive        1.0   
7          17.3        2020     USA    Diesel    All-wheel drive        1.0   
8          10.3        2016    Asia    Diesel  Front-wheel drive       -1.0   
9          10.2        2005     USA  Gasoline  Front-wheel drive       -1.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369  
5            17.271818  
6            13.210412  
7            12.848884  
8            16.823554  
9            12.298355

In [4]:
records_count = df.shape[0]
print(records_count)


9704


In [5]:
num_fuel_types = df['fuel_type'].nunique()
print(num_fuel_types)

2


In [6]:
missing_values = df.isna().sum()
print(missing_values)

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64


In [8]:
df_asia = df[df['origin'] == 'Asia']

In [9]:
max_efficiency = df_asia['fuel_efficiency_mpg'].max()
print(max_efficiency)


23.759122836520497


In [10]:
median_horsepower = df['horsepower'].median()
print(median_horsepower)


149.0


In [11]:
mode_horsepower = df['horsepower'].mode()[0]
print("Most frequent value:", mode_horsepower)


Most frequent value: 152.0


In [12]:
df['horsepower'] = df['horsepower'].fillna(mode_horsepower)


In [13]:
median_after = df['horsepower'].median()
print("Median after fillna:", median_after)


Median after fillna: 152.0


In [14]:
df_asia = df[df['origin'] == 'Asia']

print("Car number in Asia:", len(df_asia))
df_asia.head()

Car number in Asia: 3247


engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [15]:
selection = df_asia[['vehicle_weight', 'model_year']]
selection.head()


vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016

In [16]:
selected7 = selection.iloc[:7]
print("Selected 7 value\n", selected7)


Selected 7 value
     vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019


In [17]:
X = selected7.to_numpy(dtype=float)
print("X shape:", X.shape)
X


X shape: (7, 2)


array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [18]:
XTX = X.T @ X
print("XTX shape:", XTX.shape)
print("XTX =\n", XTX)


XTX shape: (2, 2)
XTX =
 [[62248334.33150762 41431216.5073268 ]
 [41431216.5073268  28373339.        ]]


In [19]:
det = np.linalg.det(XTX)
print("det(XTX) =", det)

if abs(det) > 1e-12:
    XTX_inv = np.linalg.inv(XTX)
else:
    XTX_inv = np.linalg.pinv(XTX)
print("XTX_inv =\n", XTX_inv)


det(XTX) = 49647390896215.67
XTX_inv =
 [[ 5.71497081e-07 -8.34509443e-07]
 [-8.34509443e-07  1.25380877e-06]]


In [20]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200], dtype=float)
print("y shape:", y.shape)
y


y shape: (7,)


array([1100., 1300.,  800.,  900., 1000., 1100., 1200.])

In [21]:
w = XTX_inv @ X.T @ y   
print("w (coefficients) =", w)
w_sum = w.sum()
print("Sum of elements in w =", w_sum)


w (coefficients) = [0.01386421 0.5049067 ]
Sum of elements in w = 0.5187709081074026
